use free_desktop_entry to search desktop file
pop-os/launcher pull request #216
Opened 2024-06-02 19:48 UTC by wiiznokes

This depend on https://github.com/pop-os/freedesktop-desktop-entry/pull/15.

This will have the benefit of
- one api to get all desktop files
- cache them in your struct without a wrapper
- one api to search desktop files
- localisation support for searching entries

Currently, this works really great. The searching function still need refinement, like decide what fields to include in the search, give some field more weight, ect. But any improvement will benefit all cosmic component now.

Also, idk it it's possible yet, but it will be nice to give the returned response a score so that good matches get displayed first. I think this should be managed in the frontend since there can be multiple plugin at once, but i'm not sure.

2024-06-03 11:34 UTC, mmstick commented on plugins/Cargo.toml
> -freedesktop-desktop-entry = "0.5.2"
This can be set to 0.5.3

2024-06-03 23:02 UTC, wiiznokes commented
I think having a git dependencie for fde is fine here since it will likely require some change in the matching function while cosmic approaching its release

2024-06-03 23:08 UTC, mmstick commented on plugins/Cargo.toml
> -freedesktop-desktop-entry = "0.5.2"
This is now 0.5.4

2024-06-03 23:13 UTC, wiiznokes commented on plugins/Cargo.toml
> -freedesktop-desktop-entry = "0.5.2"
Okay done

2024-06-04 13:34 UTC, mmstick requested changes

2024-06-04 13:34 UTC, mmstick commented on plugins/Cargo.toml
> -freedesktop-desktop-entry = "0.5.2"
Must update to 0.6.0 now

2024-06-04 14:45 UTC, wiiznokes commented on plugins/Cargo.toml
> -freedesktop-desktop-entry = "0.5.2"
Done

2024-06-04 15:32 UTC, mmstick approved these changes

2024-06-05 21:20 UTC, jacobgkau approved these changes
I'm not seeing any user-facing difference in search behavior while testing this.

<details>
<summary>Regression testing passed:</summary>

- [X] All windows on all workspaces appear on launch
- [X] Choosing an app on another workspace moves workspaces and focus to that app
- [X] Launching an application works
- [X] Typing text and then removing it will re-show those windows
- [X] Search works for applications and windows
- [X] Search works for GNOME settings panels
- [X] Search for "Extensions". There should be only one entry.
- [X] The overlay hint correctly highlights the selected window
- [X] Open windows are sorted above applications (e.g. "firefox")
- [X] t: executes a command in a terminal
- [X] : executes a command in sh
- [X] = calculates an equation
- [X] Search results are as expected:
    - `cal` returns Calendar and Calculator before Color
    - `pops` returns Popsicle first
    - `shop` returns the Pop!_Shop first
</details>

2024-06-05 21:25 UTC, merged