Feat/alt tab cycle
pop-os/launcher pull request #227
Opened 2024-07-13 11:00 UTC by wiiznokes

Old PR #225 

impl https://github.com/pop-os/cosmic-launcher/issues/135

With this PR, the service is not intended to be restarted everytime the cosmic-launcher is shown, because the toplevel plugin needs to keep track of some states.

So i just added a field in the plugin config:

```rs
#[serde(default)]
pub long_lived: bool,
```

For plugins that need to always running. 

And this variant Frontend -> Service/Plugin
```rs
/// The frontend was closed and the service should release resources
/// and prepare for the next query
Close,
```

I believe the service was written with this usecase in mind, so there isn't much change.

Also, i had to deactivate the sort when the query is empty.

2024-07-16 20:06 UTC, mmstick approved these changes

2024-07-17 14:04 UTC, jacobgkau reviewed
This is doing something, but the behavior seems like it needs to be tweaked a little.

1. https://github.com/pop-os/cosmic-launcher/issues/135 specifies pressing/releasing Alt-Tab should switch back and forth between the two most recent windows. I'm seeing that work sporadically, but usually, the currently selected window shows up first in the list, so pressing/releasing Alt-Tab doesn't change the window at all.
2. I'm seeing one window (titled `Oracle VM VirtualBox Manager`) basically stuck at the second or third position even after switching between many other windows (from Firefox and COSMIC Terminal) and not touching that one. So it seems like the recency-based sorting isn't working quite right, or there's somehow a way for another app/window to bypass it.

2024-07-17 14:15 UTC, jacobgkau commented
Reading https://github.com/pop-os/cosmic-launcher/issues/135, I do see it specifies applications and not windows. Let me know if we need to get UX clarification on that, if it's supposed to be working with applications right now. I think issue #1 is independent of that, based on the behavior.

2024-07-17 21:06 UTC, wiiznokes commented
Just to be sure, did you test with https://github.com/pop-os/cosmic-launcher/pull/150 ? With this PR, alt+tab will select the second app.

I was able to reproduce 2.

2024-07-17 22:06 UTC, jacobgkau commented
Ah, no I didn't. I'll get that built on CI for testing.

2024-07-17 22:46 UTC, wiiznokes commented
I think it require launcher to be located in ../launcher currently. I will change that once i fix point 2

2024-07-18 23:27 UTC, wiiznokes commented
I think there is a bug in cosmic-comp that make this PR not working:

code for the log:
```rs
ToplevelEvent::Update(handle, info) => {
                        warn!("Update {}: {:?}", &info.app_id, &info.state);
```

Output when selecting konsole -> cosmic-edit -> virtualbox -> firefox (using cosmic-launcher)

```
juil. 19 01:22:31 fedasus pop-launcher[22633]: Update org.kde.konsole: {}
juil. 19 01:22:31 fedasus pop-launcher[22633]: Update com.system76.CosmicEdit: {Activated}

juil. 19 01:22:41 fedasus pop-launcher[22633]: Update com.system76.CosmicEdit: {}
juil. 19 01:22:41 fedasus pop-launcher[22633]: Update VirtualBox Manager: {Activated}
juil. 19 01:22:41 fedasus pop-launcher[22633]: Update com.system76.CosmicEdit: {Activated}
juil. 19 01:22:41 fedasus pop-launcher[22633]: Update VirtualBox Manager: {}
juil. 19 01:22:41 fedasus pop-launcher[22633]: Update com.system76.CosmicEdit: {}
juil. 19 01:22:41 fedasus pop-launcher[22633]: Update VirtualBox Manager: {Activated}

juil. 19 01:22:45 fedasus pop-launcher[22633]: Update VirtualBox Manager: {}
juil. 19 01:22:45 fedasus pop-launcher[22633]: Update org.mozilla.firefox: {Activated}
juil. 19 01:22:45 fedasus pop-launcher[22633]: Update com.system76.CosmicEdit: {Activated}
juil. 19 01:22:45 fedasus pop-launcher[22633]: Update org.mozilla.firefox: {}
juil. 19 01:22:45 fedasus pop-launcher[22633]: Update com.system76.CosmicEdit: {}
juil. 19 01:22:45 fedasus pop-launcher[22633]: Update org.mozilla.firefox: {Activated}
```

I'm not sure this protocol is intended for this use case tho

cc @Drakulix

2024-09-25 00:31 UTC, jacobgkau requested changes
This seems to be working pretty well now.

The recency is not taking into account window activations that are a result of switching workspaces. This causes a couple of issues:

In this first video, the OBS window is never suggested as the second-most-recent window, even when I go from it directly to another window (by switching workspaces).

https://github.com/user-attachments/assets/a3ef5bef-c486-4f93-9944-32bb62472569

In this second video, even when I select a second window on that second workspace, alt-tab brings me back to the first workspace, instead of back to the previously-selected OBS window.

https://github.com/user-attachments/assets/9f240e0c-80b8-4563-a500-58621269c0b6

I think the only thing that needs to change is for the recency to take into account window activations caused by workspace switching. (Alternatively, switching could be isolated per-workspace to avoid this issue, but I don't think that was the intended design.)

2024-09-25 08:44 UTC, wiiznokes commented
probably a cosmic-comp issue @Drakulix

2024-09-25 08:50 UTC, Drakulix commented
> probably a cosmic-comp issue @Drakulix

No it isn't. The current workspace doesn't affect the `Activated` state. You need to use the `cosmic-workspace` protocol as well and track which workspace an application is on to fix this.

2024-09-25 09:37 UTC, wiiznokes commented
How would i know which top_level is active just by knowing witch workspace was activated ? Let's says there are multiple windows in workspace B. And also the case where all windows in workspace B are minimized, i guess we don't want to bump any top_level in the list.

2024-09-25 10:28 UTC, Drakulix commented
> How would i know which top_level is active just by knowing witch workspace was activated ? Let's says there are multiple windows in workspace B. And also the case where all windows in workspace B are minimized, i guess we don't want to bump any top_level in the list.

The one with the `Activated` state on said workspace of course. (Which isn't necessarily the last window to get `Activated`, just the last on said workspace, that was `Activated`.)

2024-09-25 12:01 UTC, wiiznokes commented
> The one with the Activated state on said workspace of course. (Which isn't necessarily the last window to get Activated, just the last on said workspace, that was Activated.)

I try to implement it in this branch https://github.com/wiiznokes/launcher/tree/alt-tab-with-workspace-support-1.
I does not work and i'm not sure why. I think the current behavior of both protocols make this impossible, tho, i might miss understand smtg

2024-09-25 14:29 UTC, Drakulix commented
> I try to implement it in this branch https://github.com/wiiznokes/launcher/tree/alt-tab-with-workspace-support-1. I does not work and i'm not sure why. I think the current behavior of both protocols make this impossible, tho, i might miss understand smtg

I am sorry, but I am not going to debug your branch and you are not providing me with a bunch of information.
What do you mean with "it does not work". Did you run with `WAYLAND_DEBUG=1` to figure out what events you get and when? Do you have any specific questions about the implementation.

2024-09-25 15:44 UTC, wiiznokes commented
Ok, sorry about that. I figured out the bug in my code that was causing no sense (using `position` on a reversed iterator :facepalm:). I work better now, except in this case:

1. App A in workspace X is active
2. Focus an app B in workspace Y
3. Focus an app C in workspace X

result: The list will be C -> A -> B instead of C -> B -> A, because both `WorkspaceHandler::done` and `ToplevelInfoHandler::update_toplevel` will be called

2024-09-25 16:16 UTC, Drakulix commented
> Edit: And `WorkspaceHandler::done` is called first. If it was guaranteed to be called after`ToplevelInfoHandler::update_toplevel`, that could solve this

From a cosmic-comp perspective we first swap workspaces and fixup focus afterwards, which... yeah.. I get how this is a hassle.

From a protocol perspective it is quite difficult to guarantee any specific order between the two protocols.

It might be easier to remove the `Activated`-state from the original window on workspace swap, so you can *just* rely on `cosmic-toplevel` without needing `cosmic-workspaces`.

2024-09-25 16:30 UTC, wiiznokes commented
> It might be easier to remove the Activated-state from the original window on workspace swap, so you can just rely on cosmic-toplevel without needing cosmic-workspaces.

But in my example, if the app A get focused instead of C, cosmic-toplevel will not be trigger.

2024-09-27 22:03 UTC, wiiznokes commented
@Drakulix Just to be sure, do you agree that cosmic-comp need to re send the `Activated` state when switching workspace, even we it has not _changed_ ?

2024-09-28 10:15 UTC, Drakulix commented
> @Drakulix Just to be sure, do you agree that cosmic-comp need to re send the `Activated` state when switching workspace, even we it has not _changed_ ?

Yes. Though this would also mean we remove the `Activated` state on workspace switch from the previous workspace. But that shouldn't be an issue, right?

2024-09-28 10:23 UTC, wiiznokes commented
> Yes. Though this would also mean we remove the Activated state on workspace switch from the previous workspace. But that shouldn't be an issue, right?

I don't think so. I think is it will better overall this way

2024-09-28 10:29 UTC, Drakulix commented
> > Yes. Though this would also mean we remove the Activated state on workspace switch from the previous workspace. But that shouldn't be an issue, right?
> 
> I don't think so. I think is it will better overall this way

Great. I think this *should* fix it: https://github.com/pop-os/cosmic-comp/pull/889

2024-12-09 18:09 UTC, closed without merging

2024-12-11 10:19 UTC, simonvanderveldt commented
Is my understanding correct that this has been carried/fixed via https://github.com/pop-os/cosmic-launcher/pull/225? There's no link to https://github.com/pop-os/cosmic-launcher/issues/135 nor to this PR in #225 , so I'm not really sure.

2024-12-11 22:46 UTC, simonvanderveldt commented
> Yeah your understanding is correct

OK, thanks for the confirmation and for the implementation of course :+1: