Remove "approx." keyword and improve decimal point/comma handling
pop-os/launcher pull request #70
Opened 2021-12-10 22:32 UTC by nathansgithub

This changes the calculator behavior to stop showing "approx." in front of numbers when it has more decimal places than can be shown, by enabling qalc's Unicode support. It also explicitly sets the decimal mark to decimal points when that's preferred over commas.

2021-12-14 02:31 UTC, 13r0ck commented
Thank you for the PR!
It seems though that this bug doesn't exist in Pop!_OS 21.10. As that version will be released in < 24 hours, it doesn't make sense to merge this PR.

2021-12-14 19:37 UTC, jacobgkau commented
> It seems though that this bug doesn't exist in Pop!_OS 21.10. As that version will be released in < 24 hours, it doesn't make sense to merge this PR.

We also want to consider Pop!_OS 20.04 LTS as well as other distributions. It looks like this is still happening in 20.04 LTS, so we do want to review the PR.

2021-12-14 20:18 UTC, jacobgkau requested changes
Before:
![Screenshot from 2021-12-14 13-08-58](https://user-images.githubusercontent.com/7199422/146072936-6f55f6d5-c542-4fd7-9833-78bf20798c50.png)

After:
![Screenshot from 2021-12-14 13-14-41](https://user-images.githubusercontent.com/7199422/146072943-b7b3549a-5ffd-4941-9f5c-34fa7609213a.png)

@nathansgithub Your issue https://github.com/pop-os/launcher/issues/71 indicated this should use a ≈ symbol instead of the word "approx." I don't see that ≈ symbol present, and it seems like there should be some indication when the result isn't exact. Do you know why that isn't showing?

2021-12-14 20:20 UTC, jacobgkau commented
Oh, I see, you were saying the ≈ is stripped the same was a = currently is. I think this would be a good change, if we can get the ≈ to show up in the result visually.

2021-12-14 20:34 UTC, nathansgithub commented
@jacobgkau  Yeah, I meant it uses the ≈ symbol behind the scenes. I think it's possible show the ≈ in the response. I can try that if you think that's better. If we do that, I would also add ≈ as a keyword for the calculator plugin, because I want to keep the use case where you can hit return and immediately use the previous result as part of a new calculation.

2021-12-14 21:03 UTC, jacobgkau commented
> I do want to keep the use case where you can hit return and immediately use the previous result as part of a new calculation

100% agreed on that point, that is an intended feature.

> Do you think it's important to distinguish an approximate result, and how would you want to do that?

It does seem important. I would think just having `≈ ` at the front of the result would be sufficient. (I'm pretty sure that was the behavior at some point; it might have changed when it moved from MathJS in pop-shell to qalc in pop-launcher.)

If making the launcher treat `≈` as a prefix for this plugin is the simplest way to accomplish that, then that sounds fine (pending engineering review, of course.) The other option would be getting it to only bring the rest of the result after the `≈` into the search field when pressing enter.

2021-12-14 22:50 UTC, nathansgithub commented
@jacobgkau I think this fixes it. It will leave the ≈ in front of approximate results but keep the same behavior for other results. The existing code already filters out ≈ before the value is sent to the Fill() function.

2021-12-15 02:38 UTC, nathansgithub commented
I upgraded my system to 21.10 and noticed some changes in qalc's formatting, so I added a couple changes to the code.

1. It is showing the calculation in multiple steps when the fractions can be simplified. So I changed the code to look from the right of the string for ≈ or = instead of from the left. Examples of equations that this helps normalize:
```
7 / 6 = 1 + 1/6 ≈ 1.166666667
100 / 40 = 5/2 = 2 + 1/2 = 2.5
```
2. The maximum digits after the decimal increased from 7 to 9. I explicitly set that to 9 so tests are consistent.

2022-01-24 22:06 UTC, nathansgithub commented
@jacobgkau Let me know if there's anything else you want me to change. I think this PR will make the results clearer on both 21.10 and 20.04. Right now, the equation 7/6 resolves to:
1 + 1/6 ≈ 1.166666667

2022-01-24 22:14 UTC, nathansgithub commented
@jacobgkau Let me know if there's anything else you want me to change. I think this PR will make the results clearer on both 21.10 and 20.04. Right now, the equation 7/6 resolves to:
`approx. 1.1666667` in 20.04 (the last I checked, unless qalc was updated there)
`1 + 1/6 ≈ 1.166666667` in 21.10

This change will make it so the answer on both is just `≈ 1.166666667`, which I think makes more sense and gives a more consistent behavior if you are making several calculations based off each other in the launcher.

Thanks!

2022-01-24 23:23 UTC, jacobgkau approved these changes
21.10: working as expected. Querying `2/3` returns `≈ 0.666666667`, pressing Enter on that result pre-fills `= 0.6666666667`, and from there, continuing to press Enter cycles between that and `6666666667/10000000000`.

![approx](https://user-images.githubusercontent.com/7199422/150880934-0be4eb74-a33d-4c72-a010-00e66bc6d21c.gif)

On 20.04 LTS, the behavior now looks _nearly_ identical, only (due to the older Qalculate! version) the decimal is not converted back to a fraction, so the decimal is as far as the results can go without modifying the query again:

![approx-2004](https://user-images.githubusercontent.com/7199422/150881411-cbf26442-878c-48c9-b4a0-744bbbf70248.gif)

Other calculations are still being solved as expected. This change looks good to me.

2022-01-24 23:24 UTC, mmstick approved these changes

2022-01-24 23:25 UTC, merged

2022-01-24 23:35 UTC, nathansgithub commented
Awesome, thank you!